spring:
  application:
    name: "trading"
  profiles:
    active: "test"

api:
  binance:
    description: "binance exchange api credentials"
    uri: "https://api.binance.com"
    key: "${sm://binance-api-key}"
    secret: "${sm://binance-api-secret}"



