spring:
  application:
    name: "trading"
  profiles:
    active: "test"

api:
  binance:
    description: "binance exchange api credentials"
    uri: "https://api.binance.com"
    key: "${sm://binance-api-key}"
    secret: "${sm://binance-api-secret}"

---

spring:
  config:
    activate:
      on-profile: "test"

firebase:
  service-account: "${sm://staging-firebase-service-account}"
  project-id: "trading-staging-eaee4"

api:
  bybit:
    description: "TEST NET bybit exchange test-net api credentials"
    uri: "https://api-testnet.bybit.com"
    key: "${sm://bybit-testnet-api-key}"
    secret: "${sm://bybit-testnet-api-secret}"

---

spring:
  config:
    activate:
      on-profile: "production"

firebase:
  service-account: "${sm://firebase-service-account}"
  project-id: "trading-326621"

api:
  bybit:
    description: "bybit exchange api credentials"
    uri: "https://api.bybit.com"
    key: "${sm://bybit-api-key}"
    secret: "${sm://bybit-api-secret}"