# logging
logging:
  level:
    root: WARN
    uk.co.avsoftware: DEBUG

spring:
  application:
    name: "trading"
  profiles:
    active: "local"

api:
  binance:
    description: "binance exchange api credentials"
    uri: "https://api.binance.com"
    key: "${BINANCE_KEY}"
    secret: "${BINANCE_SECRET}"

---
spring:
  profiles: production

---
spring:
  profiles: local



